### ISSUE TITLE
[Feature] S3 이미지 업로드

### ISSUE THREAD

**Issue by Huey-J** [Team-BuddyCon/BACKEND_V2#16]
아래 방식도 참고해보면 좋을 것 같아요

https://velog.io/@seeh_h/AWS-S3-presignedURL을-이용해서-image-Upload-하기-qvqo81gk

+ ref: https://techblog.woowahan.com/11392/

**Comment by shinyubin989** [comment]
서버의 부하를 줄이는 좋은 방법인것같아요! 근데 5MB 이하의 사진은 분할해서 쏠 수 없는데, 기프티콘의 경우 이미지의 크기가 5MB를 넘지 않을거라고 예상이되어서 분할해서 쏘는 방법이 효용성이 있을지 약간 고민이 됩니다!
