### ISSUE TITLE
[Fix] common 패키지 위치에 관하여..

### ISSUE THREAD

**Issue by shinyubin989** [Team-BuddyCon/BACKEND_V2#21]
저희 현재 common패키지가 app과 같은 레벨에 하나(A), app 내부에 하나(B) 이렇게 두개가 만들어져있네요..!
두개를 합쳐야하는데, A로 합칠지, B로 합칠지 짧게 의견나눠보면 좋을것같아요.
일단 저같은 경우는 common패키지에 있는 녀석들을 app외부에서는 사용하지 않고있으니 app내부의 common(B)에 합치면 좋을거같다고 생각하는데, 혹시 현희님은 어떻게 생각하실까요?
멘션 - @Huey-J

**Comment by Huey-J** [comment]
넵 그렇게 하면 될 것 같아요~ B로 가시죠

**Comment by shinyubin989** [comment]
넴~~~
